debug_and_profile_helper:
  record_list:
    - "/diagnostics"
    - "/joint_states"
    - "/debug_and_profile_helper/CLK_kinematics"
    - "/debug_and_profile_helper/CLK_computeDistances"
    - "/debug_and_profile_helper/CLK_organizeData"
    - "/debug_and_profile_helper/CLK_runController"
    - "/debug_and_profile_helper/DBG_q_dot_real"
    - "/debug_and_profile_helper/DBG_q_dot_guide"
    - "/debug_and_profile_helper/DBG_q_dot_command"
    - "/debug_and_profile_helper/DBG_distances"
    - "/debug_and_profile_helper/DBG_lambda"
  record_bag_name: "example.bag"